version: "3.2"
services:
  rest_api:
    container_name: mysql_restapi
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - WAIT_HOSTS=mysql:3306,redis:6379
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
      - DB_HOST=mysql_db
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=restapi_mysql
      - DB_NAME_TEST=restapi_mysql_test
      - PORT=5000
      - REDIS_HOST=redis_cache
    restart: always
    depends_on:
      - mysql
      - redis
    ports:
      - 5000:5000
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    hostname: mysql
    command: --default-authentication-plugin=mysql_native_password --skip-mysqlx
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: restapi_mysql
    volumes:
      - ./tmp/mysql:/var/lib/mysql
      - ./src/migrations/dbInit.sql:/docker-entrypoint-initdb.d/dbInit.sql
    ports:
      - 3306:3306
  redis:
    image: redis:alpine
    hostname: redis
    container_name: redis_cache
    restart: always
    ports:
      - 6379:6379
